# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/labfiles/Nexys4_master_DDR.xdc

# Block Designs: bd/lab1_template/lab1_template.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template || ORIG_REF_NAME==lab1_template}]

# IP: bd/lab1_template/ip/lab1_template_microblaze_0_0/lab1_template_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_microblaze_0_0 || ORIG_REF_NAME==lab1_template_microblaze_0_0}]

# IP: bd/lab1_template/ip/lab1_template_dlmb_v10_0/lab1_template_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_dlmb_v10_0 || ORIG_REF_NAME==lab1_template_dlmb_v10_0}]

# IP: bd/lab1_template/ip/lab1_template_ilmb_v10_0/lab1_template_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_ilmb_v10_0 || ORIG_REF_NAME==lab1_template_ilmb_v10_0}]

# IP: bd/lab1_template/ip/lab1_template_dlmb_bram_if_cntlr_0/lab1_template_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==lab1_template_dlmb_bram_if_cntlr_0}]

# IP: bd/lab1_template/ip/lab1_template_ilmb_bram_if_cntlr_0/lab1_template_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==lab1_template_ilmb_bram_if_cntlr_0}]

# IP: bd/lab1_template/ip/lab1_template_lmb_bram_0/lab1_template_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_lmb_bram_0 || ORIG_REF_NAME==lab1_template_lmb_bram_0}]

# IP: bd/lab1_template/ip/lab1_template_microblaze_0_axi_periph_0/lab1_template_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_microblaze_0_axi_periph_0 || ORIG_REF_NAME==lab1_template_microblaze_0_axi_periph_0}]

# IP: bd/lab1_template/ip/lab1_template_microblaze_0_axi_intc_0/lab1_template_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_microblaze_0_axi_intc_0 || ORIG_REF_NAME==lab1_template_microblaze_0_axi_intc_0}]

# IP: bd/lab1_template/ip/lab1_template_microblaze_0_xlconcat_0/lab1_template_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_microblaze_0_xlconcat_0 || ORIG_REF_NAME==lab1_template_microblaze_0_xlconcat_0}]

# IP: bd/lab1_template/ip/lab1_template_mdm_1_0/lab1_template_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_mdm_1_0 || ORIG_REF_NAME==lab1_template_mdm_1_0}]

# IP: bd/lab1_template/ip/lab1_template_xbar_0/lab1_template_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_xbar_0 || ORIG_REF_NAME==lab1_template_xbar_0}]

# IP: bd/lab1_template/ip/lab1_template_clk_wiz_1_0/lab1_template_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_clk_wiz_1_0 || ORIG_REF_NAME==lab1_template_clk_wiz_1_0}]

# IP: bd/lab1_template/ip/lab1_template_rst_clk_wiz_1_100M_0/lab1_template_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==lab1_template_rst_clk_wiz_1_100M_0}]

# IP: bd/lab1_template/ip/lab1_template_axi_timer_0_0/lab1_template_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_axi_timer_0_0 || ORIG_REF_NAME==lab1_template_axi_timer_0_0}]

# IP: bd/lab1_template/ip/lab1_template_axi_gpio_0_0/lab1_template_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_axi_gpio_0_0 || ORIG_REF_NAME==lab1_template_axi_gpio_0_0}]

# IP: bd/lab1_template/ip/lab1_template_axi_gpio_0_1/lab1_template_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_axi_gpio_0_1 || ORIG_REF_NAME==lab1_template_axi_gpio_0_1}]

# IP: bd/lab1_template/ip/lab1_template_sevenSeg_0_0/lab1_template_sevenSeg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_sevenSeg_0_0 || ORIG_REF_NAME==lab1_template_sevenSeg_0_0}]

# IP: bd/lab1_template/ip/lab1_template_mig_7series_0_0/lab1_template_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_mig_7series_0_0 || ORIG_REF_NAME==lab1_template_mig_7series_0_0}]

# IP: bd/lab1_template/ip/lab1_template_rst_mig_7series_0_81M_0/lab1_template_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==lab1_template_rst_mig_7series_0_81M_0}]

# IP: bd/lab1_template/ip/lab1_template_auto_ds_0/lab1_template_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_auto_ds_0 || ORIG_REF_NAME==lab1_template_auto_ds_0}]

# IP: bd/lab1_template/ip/lab1_template_auto_ds_1/lab1_template_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_auto_ds_1 || ORIG_REF_NAME==lab1_template_auto_ds_1}]

# IP: bd/lab1_template/ip/lab1_template_auto_ds_2/lab1_template_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_auto_ds_2 || ORIG_REF_NAME==lab1_template_auto_ds_2}]

# IP: bd/lab1_template/ip/lab1_template_auto_ds_3/lab1_template_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_auto_ds_3 || ORIG_REF_NAME==lab1_template_auto_ds_3}]

# IP: bd/lab1_template/ip/lab1_template_auto_ds_4/lab1_template_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_auto_ds_4 || ORIG_REF_NAME==lab1_template_auto_ds_4}]

# IP: bd/lab1_template/ip/lab1_template_auto_ds_5/lab1_template_auto_ds_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_auto_ds_5 || ORIG_REF_NAME==lab1_template_auto_ds_5}]

# IP: bd/lab1_template/ip/lab1_template_auto_cc_0/lab1_template_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_auto_cc_0 || ORIG_REF_NAME==lab1_template_auto_cc_0}]

# IP: bd/lab1_template/ip/lab1_template_auto_pc_0/lab1_template_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_auto_pc_0 || ORIG_REF_NAME==lab1_template_auto_pc_0}]

# IP: bd/lab1_template/ip/lab1_template_auto_us_0/lab1_template_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_auto_us_0 || ORIG_REF_NAME==lab1_template_auto_us_0}]

# XDC: bd/lab1_template/ip/lab1_template_microblaze_0_0/lab1_template_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_microblaze_0_0 || ORIG_REF_NAME==lab1_template_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/lab1_template/ip/lab1_template_microblaze_0_0/lab1_template_microblaze_0_0_ooc_debug.xdc

# XDC: bd/lab1_template/ip/lab1_template_microblaze_0_0/lab1_template_microblaze_0_0_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_dlmb_v10_0/lab1_template_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_dlmb_v10_0 || ORIG_REF_NAME==lab1_template_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/lab1_template/ip/lab1_template_dlmb_v10_0/lab1_template_dlmb_v10_0_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_ilmb_v10_0/lab1_template_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_ilmb_v10_0 || ORIG_REF_NAME==lab1_template_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/lab1_template/ip/lab1_template_ilmb_v10_0/lab1_template_ilmb_v10_0_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_dlmb_bram_if_cntlr_0/lab1_template_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_ilmb_bram_if_cntlr_0/lab1_template_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_lmb_bram_0/lab1_template_lmb_bram_0_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_microblaze_0_axi_intc_0/lab1_template_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_microblaze_0_axi_intc_0 || ORIG_REF_NAME==lab1_template_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/lab1_template/ip/lab1_template_microblaze_0_axi_intc_0/lab1_template_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_microblaze_0_axi_intc_0 || ORIG_REF_NAME==lab1_template_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/lab1_template/ip/lab1_template_microblaze_0_axi_intc_0/lab1_template_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_mdm_1_0/lab1_template_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_mdm_1_0 || ORIG_REF_NAME==lab1_template_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/lab1_template/ip/lab1_template_mdm_1_0/lab1_template_mdm_1_0_ooc_trace.xdc

# XDC: bd/lab1_template/ip/lab1_template_mdm_1_0/lab1_template_mdm_1_0_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_xbar_0/lab1_template_xbar_0_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_clk_wiz_1_0/lab1_template_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_clk_wiz_1_0 || ORIG_REF_NAME==lab1_template_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/lab1_template/ip/lab1_template_clk_wiz_1_0/lab1_template_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_clk_wiz_1_0 || ORIG_REF_NAME==lab1_template_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/lab1_template/ip/lab1_template_clk_wiz_1_0/lab1_template_clk_wiz_1_0_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_rst_clk_wiz_1_100M_0/lab1_template_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==lab1_template_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/lab1_template/ip/lab1_template_rst_clk_wiz_1_100M_0/lab1_template_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==lab1_template_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/lab1_template/ip/lab1_template_rst_clk_wiz_1_100M_0/lab1_template_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_axi_timer_0_0/lab1_template_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_axi_timer_0_0 || ORIG_REF_NAME==lab1_template_axi_timer_0_0}] {/U0 }]/U0 ]]

# XDC: bd/lab1_template/ip/lab1_template_axi_timer_0_0/lab1_template_axi_timer_0_0_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_axi_gpio_0_0/lab1_template_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_axi_gpio_0_0 || ORIG_REF_NAME==lab1_template_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/lab1_template/ip/lab1_template_axi_gpio_0_0/lab1_template_axi_gpio_0_0_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_axi_gpio_0_0/lab1_template_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_axi_gpio_0_0 || ORIG_REF_NAME==lab1_template_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/lab1_template/ip/lab1_template_axi_gpio_0_1/lab1_template_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_axi_gpio_0_1 || ORIG_REF_NAME==lab1_template_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/lab1_template/ip/lab1_template_axi_gpio_0_1/lab1_template_axi_gpio_0_1_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_axi_gpio_0_1/lab1_template_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_axi_gpio_0_1 || ORIG_REF_NAME==lab1_template_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/lab1_template/ip/lab1_template_mig_7series_0_0/lab1_template_mig_7series_0_0/user_design/constraints/lab1_template_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_template_mig_7series_0_0 || ORIG_REF_NAME==lab1_template_mig_7series_0_0}]

# XDC: bd/lab1_template/ip/lab1_template_mig_7series_0_0/lab1_template_mig_7series_0_0/user_design/constraints/lab1_template_mig_7series_0_0_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_rst_mig_7series_0_81M_0/lab1_template_rst_mig_7series_0_81M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==lab1_template_rst_mig_7series_0_81M_0}] {/U0 }]/U0 ]]

# XDC: bd/lab1_template/ip/lab1_template_rst_mig_7series_0_81M_0/lab1_template_rst_mig_7series_0_81M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==lab1_template_rst_mig_7series_0_81M_0}] {/U0 }]/U0 ]]

# XDC: bd/lab1_template/ip/lab1_template_rst_mig_7series_0_81M_0/lab1_template_rst_mig_7series_0_81M_0_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_auto_ds_0/lab1_template_auto_ds_0_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_auto_ds_0/lab1_template_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_auto_ds_0 || ORIG_REF_NAME==lab1_template_auto_ds_0}] {/inst }]/inst ]]

# XDC: bd/lab1_template/ip/lab1_template_auto_ds_1/lab1_template_auto_ds_1_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_auto_ds_1/lab1_template_auto_ds_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_auto_ds_1 || ORIG_REF_NAME==lab1_template_auto_ds_1}] {/inst }]/inst ]]

# XDC: bd/lab1_template/ip/lab1_template_auto_ds_2/lab1_template_auto_ds_2_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_auto_ds_2/lab1_template_auto_ds_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_auto_ds_2 || ORIG_REF_NAME==lab1_template_auto_ds_2}] {/inst }]/inst ]]

# XDC: bd/lab1_template/ip/lab1_template_auto_ds_3/lab1_template_auto_ds_3_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_auto_ds_3/lab1_template_auto_ds_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_auto_ds_3 || ORIG_REF_NAME==lab1_template_auto_ds_3}] {/inst }]/inst ]]

# XDC: bd/lab1_template/ip/lab1_template_auto_ds_4/lab1_template_auto_ds_4_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_auto_ds_4/lab1_template_auto_ds_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_auto_ds_4 || ORIG_REF_NAME==lab1_template_auto_ds_4}] {/inst }]/inst ]]

# XDC: bd/lab1_template/ip/lab1_template_auto_ds_5/lab1_template_auto_ds_5_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_auto_ds_5/lab1_template_auto_ds_5_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_auto_ds_5 || ORIG_REF_NAME==lab1_template_auto_ds_5}] {/inst }]/inst ]]

# XDC: bd/lab1_template/ip/lab1_template_auto_cc_0/lab1_template_auto_cc_0_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_auto_cc_0/lab1_template_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_auto_cc_0 || ORIG_REF_NAME==lab1_template_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/lab1_template/ip/lab1_template_auto_pc_0/lab1_template_auto_pc_0_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_auto_us_0/lab1_template_auto_us_0_ooc.xdc

# XDC: bd/lab1_template/ip/lab1_template_auto_us_0/lab1_template_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_template_auto_us_0 || ORIG_REF_NAME==lab1_template_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/lab1_template/lab1_template_ooc.xdc
