# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.cache/wt [current_project]
set_property parent.project_path /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /fs/student/mgdaily/Documents/ECE153/labfiles/vivado/seven/ip_repo [current_project]
add_files /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/lab1_template.bd
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_microblaze_0_0/lab1_template_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_microblaze_0_0/lab1_template_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_microblaze_0_0/lab1_template_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_dlmb_v10_0/lab1_template_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_dlmb_v10_0/lab1_template_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_ilmb_v10_0/lab1_template_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_ilmb_v10_0/lab1_template_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_dlmb_bram_if_cntlr_0/lab1_template_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_ilmb_bram_if_cntlr_0/lab1_template_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_lmb_bram_0/lab1_template_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_microblaze_0_axi_intc_0/lab1_template_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_microblaze_0_axi_intc_0/lab1_template_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_microblaze_0_axi_intc_0/lab1_template_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_mdm_1_0/lab1_template_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_mdm_1_0/lab1_template_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_mdm_1_0/lab1_template_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_xbar_0/lab1_template_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_clk_wiz_1_0/lab1_template_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_clk_wiz_1_0/lab1_template_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_clk_wiz_1_0/lab1_template_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_rst_clk_wiz_1_100M_0/lab1_template_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_rst_clk_wiz_1_100M_0/lab1_template_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_rst_clk_wiz_1_100M_0/lab1_template_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_axi_timer_0_0/lab1_template_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_axi_timer_0_0/lab1_template_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_axi_gpio_0_0/lab1_template_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_axi_gpio_0_0/lab1_template_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_axi_gpio_0_0/lab1_template_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_axi_gpio_0_1/lab1_template_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_axi_gpio_0_1/lab1_template_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_axi_gpio_0_1/lab1_template_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_mig_7series_0_0/lab1_template_mig_7series_0_0/user_design/constraints/lab1_template_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_mig_7series_0_0/lab1_template_mig_7series_0_0/user_design/constraints/lab1_template_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_rst_mig_7series_0_81M_0/lab1_template_rst_mig_7series_0_81M_0_board.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_rst_mig_7series_0_81M_0/lab1_template_rst_mig_7series_0_81M_0.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_rst_mig_7series_0_81M_0/lab1_template_rst_mig_7series_0_81M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_auto_ds_0/lab1_template_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_auto_ds_0/lab1_template_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_auto_ds_1/lab1_template_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_auto_ds_1/lab1_template_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_auto_ds_2/lab1_template_auto_ds_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_auto_ds_2/lab1_template_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_auto_ds_3/lab1_template_auto_ds_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_auto_ds_3/lab1_template_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_auto_ds_4/lab1_template_auto_ds_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_auto_ds_4/lab1_template_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_auto_ds_5/lab1_template_auto_ds_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_auto_ds_5/lab1_template_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_auto_cc_0/lab1_template_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_auto_cc_0/lab1_template_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_auto_pc_0/lab1_template_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_auto_us_0/lab1_template_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/ip/lab1_template_auto_us_0/lab1_template_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/lab1_template_ooc.xdc]
set_property is_locked true [get_files /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/lab1_template.bd]

read_verilog -library xil_defaultlib /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/sources_1/bd/lab1_template/hdl/lab1_template_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/constrs_1/imports/labfiles/Nexys4_master_DDR.xdc
set_property used_in_implementation false [get_files /fs/student/mgdaily/Documents/ECE153/Lab_1B/Lab_1B.srcs/constrs_1/imports/labfiles/Nexys4_master_DDR.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top lab1_template_wrapper -part xc7a100tcsg324-1


write_checkpoint -force -noxdef lab1_template_wrapper.dcp

catch { report_utilization -file lab1_template_wrapper_utilization_synth.rpt -pb lab1_template_wrapper_utilization_synth.pb }
